### ISSUE TITLE
Decompiled output cannot recompile do to conversion to standard form

### ISSUE THREAD

**Issue by hedavies98** [ndf-zz/disfv1#1]
When decompiling a .bin file that uses small numbers Python converts this to standard form in the output which SpinAsm doesn't recognise as a number.

For example the program outputs:
`rdfx    REG2,6.103515625e-05    ; reg:0x22 k:0x0001`

When instead it should output:
`rdfx    REG2,0.00006103515625    ; reg:0x22 k:0x0001`

It's not a big deal to fix this manually after disassembly but it would be nice for the program to output numbers in the correct form.

**Comment by ndf-zz** [comment]
Hi, thanks for your suggestion and sorry for the very slow response - I'll make that change and update soon.
